### ISSUE TITLE
[Bug]: Looking for loader by default

### ISSUE THREAD

**Issue by sozonome** [web-infra-dev/rsdoctor#155]
### Version

```sh
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 297.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 119.0.6045.105
    Firefox: 120.0
    Firefox Developer Edition: 118.0
    Safari: 17.1.2
  npmPackages:
    @rsdoctor/rspack-plugin: ^0.1.0 => 0.1.0
```

### Details

I tried to follow the [Quick Start](https://rsdoctor.dev/guide/start/quick-start) guide on my rsbuild react project.
But when I try to run `RSBUILD=true rsbuild build`, it keeps outputting error like this:

```bash
info    Ts checker running...
info    Ts checker is running slowly and will block builds until it is complete, please be patient and wait.
error   Failed to build.
error   TypeError: Cannot read properties of undefined (reading 'startsWith')
    at /projects/react-chakra-rsbuild/node_modules/.pnpm/@rspack+core@0.5.0_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/config/adapterRuleUse.js:48:24
```

I try to see adapterRuleUse.js and it looks for `loader`
Then I try to read further on the rsdoctor configuration documentation and found [this section](https://rsdoctor.dev/config/options/index#features)

After adding this configuration:
```ts
// rsbuild.config.ts
export default defineConfig({
  ...
  tools: {
    // https://rsbuild.dev/config/plugins#rspack-plugins
    rspack: {
      plugins: [
        ...,
        new RsdoctorRspackPlugin({
          features: {
             loader: false,
          },
        }),
      ].filter(Boolean),
    },
  },
});
```

It work correctly.

I believe this could be improved by:
- [Alt 01] telling the audience to set the loader to false if there's no loader being used in Quick Start guide.
- [Alt 02] make it false by default

Correct me if this is intentional, as I believe other people who use rsbuild and want to try rsdoctor might encounter this issue and having hard time what to do.

### Reproduce link

https://github.com/sozonome/rsbuild-react-chakra-starter/blob/main/rsbuild.config.ts#L26

### Reproduce Steps

1. Follow Quick Start guide
2. Configure rsbuild.config.ts to use RsdoctorRspackPlugin
3. run `RSBUILD=true rsbuild build`

**Comment by easy1090** [comment]
Thx~ I will check and fix this problem.

**Comment by SoonIter** [comment]
It seems that under the proxy-loader wrapper of rsdoctor, rspack is unable to correctly handle rules where 'use' is of function type.

some context here, millionjs-plugin is an "unplugin", "use" is a function type.


https://github.com/unjs/unplugin/blob/3b05d441065741639a68d06ec6eed74c36790e65/src/rspack/index.ts#L83
https://github.com/web-infra-dev/rspack/blob/cb73ba498364e7f9d89426e1b03abddc577de1a5/packages/rspack/src/config/adapterRuleUse.ts#L281
