### ISSUE TITLE
[Feature]: Custom export behaviour for Gitlab pages

### ISSUE THREAD

**Issue by YanPes** [web-infra-dev/rsdoctor#157]
### What problem does this feature solve?

As a customer I want to publish the Rsdoctor report on a Gitlab Pages page or a custom hosting solution to be able to access the generated reports from outside. This will help customers monitor the running applications without the need of a local running system.

Acceptance:
- Create a output behaviour to generate a static dist folder in the project directory
- The plugin option has a new parameter to toggle the static export behaviour
- Customers can use the dist export for Gitlab pages or a custom hosting

### What does the proposed API look like?

**New plugin option:**
```
new RsdoctorRspackPlugin({
      [...],
      staticExport: true
    }),
```

**Generated static files for usage:**
// my-repository-path/dist/rsdoctor/index.html
// my-repository-path/dist/rsdoctor/main.css
// my-repository-path/dist/rsdoctor/main.js

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/462
- [ ] Generate the biref page for rsdoctor.
```

**Comment by easy1090** [comment]
Good idea! I'll include this in the plan. 
Perhaps you only need to report assets once. If you need historical assets, you should keep the reports.

**Comment by YanPes** [comment]
Thank you for the fast action on this request. Really appreciate it!

**Comment by YanPes** [comment]
@easy1090 any rough idea when this will be implemented?

**Comment by easy1090** [comment]
At present, in May, the high-priority requirement of Rsdoctor is to improve the efficiency of build analysis on webpack or rspack, but the ability of custom report will be realized in June or July.

Currently, the data of Rsdoctor is too large, which may cause the page to crash, so a streamlined page export is required for the custom report.

In June, the ability of the Rsdoctor plugin system will be provided. During the construction process, users can obtain and operate the Rsdoctor analysis data by themselves:
```js

// xxx.config.js
 new RsdoctorWebpackPlugin({
      extends: [RsdoctorCustomPlugin]
 })
 
 
 // rsdoctorCustomPlugin.ts
 
 const RsdoctorCustomPlugin = definePlugin(() => ({
  handle(data) {
    // .. do something with the data context， the data includes rsdoctor's all analysis data.
  },
}));

```

**Comment by YanPes** [comment]
@easy1090 Thank you for the insights on the current development! I will check out the custom plugin approach. Appreciate your efforts! 🥳

**Comment by easy1090** [comment]
You can use rsdoctor's brief mode, @rsdoctor/* > 0.4.0, https://rsdoctor.dev/guide/start/cicd
