### ISSUE TITLE
[Bug]: Run Error

### ISSUE THREAD

**Issue by luoriwusheng-xia** [web-infra-dev/rsdoctor#158]
### Version

```sh
window 10
node: 20.10.0
```

```
"@rsdoctor/rspack-plugin": "^0.1.0",
"@rspack/cli": "^0.5.2",
"@rspack/core": "^0.5.2",
```

Warehouse for reproducing problems
复现问题的仓库

https://gitee.com/luoriwusheng/vue-element-admin
```


### Details

![image](https://github.com/web-infra-dev/rsdoctor/assets/152823466/5ff3faff-a749-4f41-94e0-58039c8d430c)

Before being introduced, the project was running normally
没有加入这个插件之前，项目正常运行

The service can get up, but there is an error on the console
服务能起来，但是控制台有报错

![image](https://github.com/web-infra-dev/rsdoctor/assets/152823466/f9f49c18-82d5-4efd-b95d-a649fb4b1278)




### Reproduce link

https://gitee.com/luoriwusheng/vue-element-admin

### Reproduce Steps

1. clone  repo
2. npm i
3. npm run doctor

**Comment by easy1090** [comment]
Please pay attention to this issue #20 , and I will support it with high priority.

**Comment by luoriwusheng-xia** [comment]
> Please pay attention to this issue #20 , and I will support it with high priority.请注意这个问题#20，我将优先支持它。

ok  ok , thanks!

If a new version is released, you can go to my repository to try it out. All rspack related packages in the repository are currently the latest.
[zh-cn] 如果发布了新版本 ,可以去我的仓库尝试一下，仓库中所有rspack相关的包目前均为最新。

**Comment by luoriwusheng-xia** [comment]
yes ， After verification in the warehouse, the issue has been fixed
