### ISSUE TITLE
[Bug]: hmr hot update will reopen a new window. 

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#159]
### Version

```sh
@rsdoctor/webpack-plugin: 0.1.0
@rsdoctor/rspack-plugin: 0.1.0
```

### Details

When dev mode, hmr hot update will reopen a new window, but the port is the same.

**Comment by SoonIter** [comment]
I have gained some experience from this file; package "open" will always open a new tab, perhaps we can make some improvements based on this file.

https://github.com/vitejs/vite/blob/3fceb14b94b12d12d47285402980f360aa4284ea/packages/vite/src/node/server/openBrowser.ts#L23

**Comment by chenjiahan** [comment]
@SoonIter also this: https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/plugins/startUrl.ts
