### ISSUE TITLE
[Bug]Rsdoctor loader analysis will throw error when rspack with vue-loader.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#20]
**demo:**
rsbuild use rspack@0.3.14 builder + vue-loader + @rsbuild/doctor-rspack-plugin@0.0.14
**error:**
<img width="1370" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/18437716/0648f5e1-de96-47f3-901d-bdca9797ade2">

**Comment by SoonIter** [comment]
get another error

<img width="1272" alt="image" src="https://github.com/web-infra-dev/rsdoctor/assets/79413249/56741ff9-7136-46b3-a70c-db3f1e2184ba">
<img width="1247" alt="image" src="https://github.com/web-infra-dev/rsdoctor/assets/79413249/e4476483-3b2b-4903-8402-71a671a10d8c">
