### ISSUE TITLE
[Bug]: Build in webpack + production mode stuck when rsdoctor is enabled.

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rsdoctor#206]
### Version

```sh
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 8.01 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Edge: 122.0.2365.80
    Safari: 17.3.1
```

### Details

Hello, I enabled the rsdoctor/webpack-plugin and triggered a webpack + production build. 
I can see the live build-analysis ongoing along with the build. However, I do not see the build ever completing and seems like it is stuck forever. 
FYI, I switched the features to [lite, loader, plugins] to avoid any OOM issues. 
I also tried by disabling the disableClientServer , but still the build is stuck. I waited for ~2-3 hours for a build which typically takes around 15 minutes to complete. 

Its stuck at "52.1% building" as shown in the below image:
![image](https://github.com/web-infra-dev/rsdoctor/assets/93791633/0664e18a-1fba-406d-b975-0efcf264552e)

### Reproduce link

N/A

### Reproduce Steps

enable @rsdoctor/webpack-plugin for a webpack build in production mode.

**Comment by easy1090** [comment]
This problem may occur under the construction of super-large projects, because Loader reporting will increase the time. We have expected to rust under rspack next quarter to optimize this problem.

This problem seems to be that the compilation stage is relatively heavy, and a specific case needs to be provided. I don't know if it is convenient to provide it.

After the construction is completed, you can also use @rsdoctor/cli to open the report and provide the loader time-consuming data to see which loaders take more time.

**Comment by pushkargupta9807** [comment]
Thank @easy1090 . So is there a way I can create the html report file without enabling the devClientServer and just running the build end to end? If so can you lay out the steps please. Thanks

**Comment by easy1090** [comment]
@pushkargupta9807 Yes, you can set disableClientServer to true to build without opening the report. After the build is completed, it will be in the build product directory .rsdoctor/manifest.json file. But when you want to open the report, you can use @rsdoctor/cli to open the report without building it: https://rsdoctor.dev/guide/start/cli
```
npx @rsdoctor/cli analyze --profile [.rsdoctor/manifest filepath]
```

**Comment by pushkargupta9807** [comment]
Thank you @easy1090 . I tried that , but for my current app the build never ends and the manifest.json file is never generated. 

I tried to scale down the features as well - as in the above config , but it still gets stuck.

**Comment by pushkargupta9807** [comment]
@easy1090 I think it is the loaders analysis which is making the build get stuck after compilation is complete.  When I just use other features like [plugins] , the build completes with analysis. 

As such I was wondering , do you have any insights so as to what might be causing the loader analysis getting stuck forever ?  Any way I can debug the InternalLoaderPlugin below to see see what is causing it to never finish ? Or any other tips 

![image](https://github.com/web-infra-dev/rsdoctor/assets/93791633/8fd8379a-f87b-4f5c-ae15-fc1374d655f4)

**Comment by easy1090** [comment]
> Also I observe that the "@rsdoctor/core/plugins" is not present - is that expected?

This problem has been fixed #305. You can use the 0.2.0 version, current this version is a beta tag.

> the loaders analysis which is making the build get stuck after compilation is complete

This problem is not meet yet. Can u give me your repo , I'll try to check this problem. Or you can give me your webpack.config.js. And whether your project has used Vue??

**Comment by easy1090** [comment]
You can try to use this options:
```ts
reportCodeType： {
   noCode: true
}
```

https://rsdoctor.dev/config/options/options#reportcodetype

**Comment by pushkargupta9807** [comment]
Thank you! will try and let you know.

**Comment by easy1090** [comment]
Too long no reply，will close this issue. If also has this problem, can open again.
