### ISSUE TITLE
Documentation/Questions

### ISSUE THREAD

**Issue by Banner-Keith** [web-infra-dev/rsdoctor#228]
### What problem does this feature solve?

I didn't see a discussions section on this repo and have some questions that I couldn't find answers to on the documentation site, existing issues, or by perusing the code.

First of all, what is `disableTOSUpload`. Is data from the plugin being uploaded somewhere? I'm guessing just to the local running server.

Second, I get this bundle alert: "The ECMA version of asset main.bdc21c64a759c5cc2e9a.js is ES7+, which is bigger than ES5."

I'm a bit confused by that one as it seems like the explanation of this rule "Detect if there is a low version of ECMA syntax in the js bundle file" would flag older versions of ECMA. What am I missing?

### What does the proposed API look like?

N/A

**Comment by easy1090** [comment]
- disableTOSUpload： this is a property for bytedance company inner use, to upload the data to cdn, then users can use the online data. This property I'll delete on this repo's Rsdoctor.
-  Thanks for your issue，the explanation of this rule "Detect if there is a low version of ECMA syntax in the js bundle file" is wrong, I'll fix it.
