### ISSUE TITLE
[Feature]: Add port configuration option

### ISSUE THREAD

**Issue by daveskybet** [web-infra-dev/rsdoctor#257]
### What problem does this feature solve?

When working inside docker containers, the current random approach for assigning a port number makes things a little tricky when opening port numbers inside a docker compose file (for example). Allowing users to provide a port number of their choosing would alleviate this problem. 

### What does the proposed API look like?

There are a few ways this could be done, adding a `port` option in the options config, or an env var are two that spring to mind.

**Comment by easy1090** [comment]
OK, I will put this issue in the TODO List, please pay attention to it.
