### ISSUE TITLE
[Bug]:  Failed to parse the CSS files 

### ISSUE THREAD

**Issue by saravanan10393** [web-infra-dev/rsdoctor#264]
### Version

```sh
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 530.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 122.1.63.162
    Edge: 122.0.2365.59
    Safari: 17.3
  npmPackages:
    @rsdoctor/webpack-plugin: ^0.1.8 => 0.1.8
```

### Details

ModuleParseError: Module parse failed: Unexpected token (5:0)
File was processed with these loaders:
 * ../../node_modules/.pnpm/@rsdoctor+core@0.1.8_@swc+core@1.4.11/node_modules/@rsdoctor/core/dist/inner-plugins/loaders/proxy.js
You may need an additional loader to handle the result of these loaders.
| /* stylelint-disable */
| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
> .ant-btn {
|   line-height: 1.5715;
|   position: relative;

### Reproduce link

--

### Reproduce Steps

--

**Comment by easy1090** [comment]
Can you provide the problem's demo?
Or what technology stacks are used in the project?

**Comment by easy1090** [comment]
As the issue was labelled with `need reproduction`, but no response in 5 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions. For background, see [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

            由于该 issue 被标记为 "需要重现"，但在 5 天内没有回应，因此该 issue 将被关闭。如果你有任何进一步的问题，请随时发表评论并重新打开该 issue。背景请参考 [为什么需要最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)。
