### ISSUE TITLE
[Feature]: Add Rsdoctor to Rspack ecosystem CI

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsdoctor#29]
### What problem does this feature solve?

Add Rsdoctor to: https://github.com/web-infra-dev/rspack-ecosystem-ci

So if Rspack introduces some breaking changes or regressions, Rsdoctor can detect and repair in advance.

### What does the proposed API look like?

Send a PR to rspack-ecosystem-ci repo.

**Comment by easy1090** [comment]
mr: https://github.com/rspack-contrib/rspack-ecosystem-ci/pull/65
