### ISSUE TITLE
[Bug]: The file name in rule check's logs is undefined.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#350]
### Version

```sh
@rsdoctor/* 0.2.4
```

### Details

<img width="539" alt="image" src="https://github.com/web-infra-dev/rsdoctor/assets/18437716/83db6e48-1007-48d6-8241-70dc4e0e4837">

### Reproduce link

empty

### Reproduce Steps

just build with rsdoctor.

**Comment by easy1090** [comment]
@9aoy  Please cc this issue. I found that there will only be this problem under rsbuild:
<img width="504" alt="image" src="https://github.com/web-infra-dev/rsdoctor/assets/18437716/54988a4e-74f5-4a0f-8c9d-8953843013d2">

rspack：
<img width="466" alt="image" src="https://github.com/web-infra-dev/rsdoctor/assets/18437716/4e8ecd4c-baee-4b72-9c4c-70f9d8cce912">

**Comment by 9aoy** [comment]
@easy1090 this problem already fixed, you can upgrade rsbuild to [0.7.2](https://github.com/web-infra-dev/rsbuild/releases/tag/v0.7.2).

fixed by: https://github.com/web-infra-dev/rsbuild/pull/2463
