### ISSUE TITLE
[Bug]: Large loader data can not open the loader analysis page

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#426]
### Version

```sh
rsdoctor -> v0.3.x
```

### Details

Large loader data can not open the loader analysis page . related mr: #167

**Comment by pushkargupta9807** [comment]
Thank you for fixing the earlier bug and opening this new one to address the issue where larger loader data does not load.

**Comment by easy1090** [comment]
First of all, I'm sorry to keep you waiting. Brief Report will be released next week. Brief Report can check the time of loader, but it can't check the compile code changes of loader for each file. @pushkargupta9807

**Comment by easy1090** [comment]
You can try to use this options:
```ts
reportCodeType： {
   noCode: true
}
```

https://rsdoctor.dev/config/options/options#reportcodetype

**Comment by easy1090** [comment]
Too long no reply，will close this issue. If also has this problem, can open again.
