### ISSUE TITLE
[Bug]: Can I hide the server running tip?

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rsdoctor#427]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 658.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Details

I want to hide this tip
![image](https://github.com/user-attachments/assets/470ef23a-f3f7-4c0d-a263-258f6c784c43)

### Reproduce link

https://github.com/

### Reproduce Steps

run build

**Comment by easy1090** [comment]
Please tell me the reason why you want to hide it? @dingff

**Comment by dingff** [comment]
The log style is different from my cli style, they look weird together. @easy1090

**Comment by easy1090** [comment]
ok， i'll add a options to control this.

**Comment by easy1090** [comment]
@dingff  can use this options: https://github.com/web-infra-dev/rsdoctor/blob/main/examples/rsbuild-minimal/rsbuild.config.ts#L31

**Comment by dingff** [comment]
> @dingff can use this options: https://github.com/web-infra-dev/rsdoctor/blob/main/examples/rsbuild-minimal/rsbuild.config.ts#L31

I can't wait

**Comment by easy1090** [comment]
tomorrow will pubish the v 0.3.11
