### ISSUE TITLE
[Feature]: Is there a way to set the output directory when using the webpack plugin?

### ISSUE THREAD

**Issue by FlowingPond** [web-infra-dev/rsdoctor#442]
### What problem does this feature solve?

The output directory can only be **".rsdoctor"** now. When I run multiple webpack compilers simultaneously, the outputs seem to be overwritten.

### What does the proposed API look like?

Maybe you can add a field in the webpack plugin's configuration options to set the output directory?

**Comment by easy1090** [comment]
You can use  RsdoctorRspackMultiplePlugin like https://github.com/web-infra-dev/rsdoctor/blob/main/examples/multiple-minimal/build.ts

I'll add this usage on document later.

The option `stage` is 
- stage:
Type: Number

Optional: true

Default: 0

Description: The display order of the builder report, the smaller the number, the higher the priority. Only BytedRsdoctorMultiPlugin has this stage property.

**Comment by FlowingPond** [comment]
Got it, I'll give it a try later. Thanks!
