### ISSUE TITLE
[Feature]: Bundle analysis - support sort by size

### ISSUE THREAD

**Issue by nhducit** [web-infra-dev/rsdoctor#469]
### What problem does this feature solve?

Thank you, team, for the excellent tool. Would you consider adding a size-based sorting option to the bundle analysis result page? 

This feature would help users focus on the most impactful dependencies first.

![CleanShot 2024-08-13 at 19 29 24@2x](https://github.com/user-attachments/assets/012c2874-ff3f-464a-a09b-94287f938bcb)

I will send a PRs if we are cool with the idea

### What does the proposed API look like?

Check the screenshot above for suggestion

**Comment by easy1090** [comment]
Thank you for your advice. Looking forward to your pr~
