### ISSUE TITLE
[Feature]: Loader analysis provide support for Rspack layers

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsdoctor#566]
### What problem does this feature solve?

The loader analysis page should provide support for Rspack layers.

See https://rspack.dev/config/experiments#experimentslayers

### What does the proposed API look like?

Currently, if a project uses Rspack layers, the loader analysis result will be inaccurate, I will try to provide a minimal reproduction later.

**Comment by chenjiahan** [comment]
A minimal example of using layers + Rsdoctor:

https://github.com/chenjiahan/rsdoctor-repro-loader-layers

Currently all loaders from different layers are mixed together. We expect to separate them and mark the `layers` id in the UI.

![Image](https://github.com/user-attachments/assets/79934f75-b0a9-469e-b9f5-c61df7b0789e)

**Comment by easy1090** [comment]
related mr : 
1. rspack support the layer : https://github.com/web-infra-dev/rspack/pull/8283
2. rsdoctor support the layer data: https://github.com/web-infra-dev/rsdoctor/pull/583
