### ISSUE TITLE
[Bug]:  RsDoctor does not display the count of JS and CSS files in output

### ISSUE THREAD

**Issue by dakiesse** [web-infra-dev/rsdoctor#586]
### Version

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.84 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 128.1.69.168
    Chrome: 130.0.6723.92
    Safari: 18.0.1
    Safari Technology Preview: 18.0
  npmPackages:
    @rsdoctor/rspack-plugin: ^0.4.8 => 0.4.8 

### Details

I came across that RsDoctor does not show the number of JS and CSS files, and brakes the stats with the following rspack config:

```javascript
output: {
    filename: '[name].js?v=[contenthash]',
    chunkFilename: '[name].js?v=[contenthash]',
    ...,
},
plugins: [
    new rspack.CssExtractRspackPlugin({
        filename: '[name].css?v=[contenthash]',
        chunkFilename: 'styles.[name].css?v=[contenthash]',
    }),
    ...,
]
```

Result:
![Image](https://github.com/user-attachments/assets/5dc77f88-426c-49b8-a836-56d8435193cc)
![Image](https://github.com/user-attachments/assets/18184322-e002-4123-b6e3-d39448a5ca8e)

But if i use:
```javascript
output: {
    filename: '[name].[contenthash].js',
    chunkFilename: '[name].[contenthash].js',
    ...,
},
plugins: [
    new rspack.CssExtractRspackPlugin({
        filename: '[name].[contenthash].css',
        chunkFilename: 'styles.[contenthash].[name].css',
    }),
    ...,
]
```

Result OK:
![Image](https://github.com/user-attachments/assets/1808e3b8-dc37-4539-b5d3-3256fd02416b)
![Image](https://github.com/user-attachments/assets/b8cf72b2-fd02-41f2-a4e1-b535449f9cb3)

### Reproduce link

.

### Reproduce Steps

.

**Comment by easy1090** [comment]
Got this issue, I'll reappear this scene and solve it.

**Comment by easy1090** [comment]
This is has been fixed. Add version is 0.4.11.
