### ISSUE TITLE
[Bug]: Rsdoctor App Development Experience Issues

### ISSUE THREAD

**Issue by nyqykk** [web-infra-dev/rsdoctor#595]
### Version

```sh
pass
```

### Details

1. `HMR` build time is too long, about 5s, so slowly.

2. `Fast Refresh` is not available, just reload, after build cause 5s, we still need to wait `location.reload` which greatly affects the development experience.
3. Too much warning in terminal, and after `HMR`, this modal always auto open.
![Image](https://github.com/user-attachments/assets/094f692d-754a-40b7-b072-f5650fda6042)
 

### Reproduce link

pass

### Reproduce Steps

pass

**Comment by fireairforce** [comment]
it seems a little awful... :(

**Comment by nyqykk** [comment]
1. Use dev command `pnpm dev` instead of `ENABLE_DEVTOOLS_PLUGIN=true ENABLE_CLIENT_SERVER=true pnpm run dev`
2. Use online data for local dev instead of using local build data https://github.com/web-infra-dev/rsdoctor/blob/main/packages/components/src/utils/request.ts#L84
