### ISSUE TITLE
[Bug]: node14，vuecli5使用@rsdoctor/webpack-plugin运行错误

### ISSUE THREAD

**Issue by agreenbird1** [web-infra-dev/rsdoctor#631]
### Version

```sh
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 31.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.110
    Edge: 131.0.2903.86
    Safari: 16.3
  npmPackages:
    @rsdoctor/webpack-plugin: ^0.4.11 => 0.4.11
```

### Details

直接使用vuecli5创建一个vue3的项目。vue.config.js中配置
```
const { defineConfig } = require("@vue/cli-service");
const { RsdoctorWebpackPlugin } = require("@rsdoctor/webpack-plugin");

module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    plugins: [new RsdoctorWebpackPlugin()],
  },
});
```

运行 `pnpm run build`，控制台报错`Error: Cannot find module 'node:child_process'` at openBrowser.js，但是我查了文档和依赖项没看见有约束node版本的范围。手动改了模块的引入方式后继续打包，`Syntax Error: Thread Loader (Worker 0)
Cannot read property 'reportLoaderStartOrEnd' of undefined`，加了可选链语法后运行正常。

### Reproduce link

https://github.com/agreenbird1/rsdoctor-vue-cli5

### Reproduce Steps

node@14 pnpm@7

**Comment by Ininit** [comment]
Syntax Error: Thread Loader (Worker 0) Cannot read property 'reportLoaderStartOrEnd' of undefined 这个错误不是 node 版本问题， 使用 thread-loader 后 getSDK 一直是 `undefined`

**Comment by easy1090** [comment]
哦哦，确实 rsdoctor 不支持使用 thread-loader  哈，感谢回复~我们文档里注明下❤

**Comment by Ininit** [comment]
> 哦哦，确实 rsdoctor 不支持使用 thread-loader 哈，感谢回复~我们文档里注明下❤

原来如此，感觉可以在 `addProbeLoader2Rules` 判断一下 `rule.use` 如果有 `thread-loader`，那么在 `thread-loader`之后的 `loader` 不附加 `ProbeLoader` 。
