### ISSUE TITLE
[Bug]: Loader Analysis failed and the console reported an error

### ISSUE THREAD

**Issue by idy1000** [web-infra-dev/rsdoctor#652]
### Version

```sh
System:
  OS: macOS 13.6.3
  CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Memory: 20.18 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 131.0.6778.205
  Safari: 16.6
npmPackages:
  @rsdoctor/rspack-plugin: ^0.4.12 => 0.4.12
```

### Details

<img width="1679" alt="Image" src="https://github.com/user-attachments/assets/4b21dd69-bdc4-43b6-b4a0-1b0857905c1e" />
Loader Analysis失败，显示loading，控制台有报错

### Reproduce link

https://rsbuild.dev/guide/start/quick-start

### Reproduce Steps

rsbuild随便一个test即可复现

**Comment by easy1090** [comment]
What version of rsbuild?

**Comment by idy1000** [comment]
> What version of rsbuild?

1.1.10

**Comment by easy1090** [comment]
<img width="988" alt="Image" src="https://github.com/user-attachments/assets/eaee591a-6e41-4900-8d39-e56f97ef374a" />
I just created a dlemo that has not been reproduced. Is it a VUE technology stack?

**Comment by easy1090** [comment]
<img width="890" alt="Image" src="https://github.com/user-attachments/assets/6d43bfa9-5152-4655-94a8-aad1fd3259e8" />
I guess this maybe a problem of network:
https://github.com/suren-atoyan/monaco-react/issues/169#issuecomment-764548617

**Comment by idy1000** [comment]
![Image](https://github.com/user-attachments/assets/f360dcaa-9861-47fb-8494-c4819aabaa23)
确实是网络问题，尝试等这个js加载好后，就没有问题了
谢谢解答
