### ISSUE TITLE
[Feature]Create @rsbuild/doctor-cli as open report platform entry command package.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#7]
Create @rsdoctor/cli as open report platform entry command package, this has three commands:
- analyze --profile [doctor's manifest.json filepath]
- stats-analyze --profile [webpack or rspack stats.json filepath]
- bundle-diff --baseline=[baseline filepath] --current=[current filepath] 

Utilize the cli command to invoke the reporting platform.

**Comment by maxyasoon** [comment]
Is it still planned to support the stats-analyze and bundle-diff command?
