### ISSUE TITLE
[Bug]: missing @rsdoctor/types when using @rsdoctor/webpack-plugin

### ISSUE THREAD

**Issue by alyahmedaly** [web-infra-dev/rsdoctor#73]
### Version

```sh
npmPackages:
    @rsdoctor/client: ^0.0.2-beta.0 => 0.0.2-beta.0 
    @rsdoctor/types: ^0.0.2-beta.0 => 0.0.2-beta.0 
    @rsdoctor/webpack-plugin: ^0.0.2-beta.0 => 0.0.2-beta.0
```

### Details

I was trying out rsdoctor today on my webpack app Thanks for the great tool,

I found out that I need to install `@rsdoctor/types` as it's missing dependancy from `@rsdoctor/webpack-plugin`

```
[webpack-cli] Error: Cannot find module '@rsdoctor/types'
Require stack:
- ./node_modules/@rsdoctor/utils/dist/cjs/logger/logger.js
- ./node_modules/@rsdoctor/utils/dist/cjs/logger/index.js
- ./node_modules/@rsdoctor/core/dist/build-utils/common/chunks/assetsModules.js
```

### Reproduce link

no need :)

### Reproduce Steps

install and run @rsdoctor/webpack-plugin

**Comment by chenjiahan** [comment]
Thanks for the feedback! We will check this soon.

**Comment by easy1090** [comment]
The latest version has fix this.[0.0.2-beta.1](https://www.npmjs.com/package/@rsdoctor/webpack-plugin/v/0.0.2-beta.1)
